from fate_of_dice.common.exception import DiceException


class RollException(DiceException):
    pass
